4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(value, conversion_type):
    """
    Convert units based on the selected conversion type.

    Parameters:
    value (float): The numeric value entered by the user to convert.
    conversion_type (int): The conversion option selected by the user.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:  # meters to feet
        return value * 3.28084
    elif conversion_type == 2:  # feet to meters
        return value / 3.28084
    elif conversion_type == 3:  # kg to pounds
        return value * 2.20462
    elif conversion_type == 4:  # pounds to kg
        return value / 2.20462
    elif conversion_type == 5:  # liters to gallons
        return value * 0.264172
    elif conversion_type == 6:  # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("-----------------------")

    print("Select conversion type:")
    print("1. Meters (m) to Feet (ft)")
    print("2. Feet (ft) to Meters (m)")
    print("3. Kilograms (kg) to Pounds (lbs)")
    print("4. Pounds (lbs) to Kilograms (kg)")
    print("5. Liters (L) to Gallons (gal)")
    print("6. Gallons (gal) to Liters (L)")

    try:
        choice = int(input("Enter your choice (1-6): "))

        if choice < 1 or choice > 6:
            print("Error: Unsupported conversion type.")
            return

        value = float(input("Enter the value to convert: "))

        result = convert_units(value, choice)

        if result is not None:
            print(f"Converted value: {result:.4f}")
        else:
            print("Conversion could not be performed.")

    except ValueError:
        print("Error: Invalid input. Please enter numeric values only.")


if __name__ == "__main__":
    main()

Unit Conversion Program
-----------------------
Select conversion type:
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)
5. Liters (L) to Gallons (gal)
6. Gallons (gal) to Liters (L)
Enter your choice (1-6): 1
Enter the value to convert: 1
Converted value: 3.2808


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(numbers):
    """
    Calculate the sum of numbers in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of all numbers in the list.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of numbers in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Find the maximum value in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Maximum number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Find the minimum value in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Minimum number in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List of Numbers")
    print("--------------------------------------------")

    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        numbers_input = input("Enter numbers separated by spaces: ")

        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            result = find_sum(numbers)
            print("Sum:", result)

        elif choice == 2:
            result = find_average(numbers)
            print("Average:", result)

        elif choice == 3:
            result = find_max(numbers)
            print("Maximum:", result)

        elif choice == 4:
            result = find_min(numbers)
            print("Minimum:", result)

        else:
            print("Error: Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values.")


if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
--------------------------------------------
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 5 5 10
Sum: 20.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list of elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Return a sublist from the given list between the start and end indices (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index of the sublist.
    end (int): Ending index of the sublist.

    Returns:
    list: A sublist containing elements from start to end (inclusive).
    """
    return lst[start:end+1]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The input list to be reversed.

    Returns:
    list: A new list that is the reverse of the input list.
    """
    return lst[::-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements from a list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Original list:", numbers)
print("Resulting list:", result)

Original list: [1, 2, 3, 4, 5]
Resulting list: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Return the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the beginning.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Original list:", numbers)
print("First n elements:", result)

Original list: [1, 2, 3, 4, 5]
First n elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Return the last n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Original list:", numbers)
print("Last n elements:", result)

Original list: [1, 2, 3, 4, 5]
Last n elements: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Extract elements in reverse order starting from the second-to-last element,
    skipping one element in between.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element from the second-to-last,
    moving backward.
    """
    return lst[-2::-2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Result:", result)

Original list: [1, 2, 3, 4, 5, 6]
Result: [5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
    lst (list): A nested list containing sublists.

    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example usage
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices that specify the position of the element.

    Returns:
    any: The element found at the specified indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


# Example usage
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)

print("Element at given indices:", result)

Element at given indices: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all elements in a nested list.

    Parameters:
    lst (list): A list that may contain numbers or other nested lists.

    Returns:
    int/float: The total sum of all numbers in the nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item

    return total


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Sum of all elements:", result)

Sum of all elements: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list that may contain sublists.
    elem (any): The element to be removed.

    Returns:
    list: A new nested list with all occurrences of elem removed.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # Recursively process sublists
        else:
            if item != elem:
                result.append(item)

    return result


# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

output = remove_element(lst, elem)

print("Modified list:", output)

Modified list: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
    lst (list): A list that may contain numbers or other nested lists.

    Returns:
    int/float: The maximum number found in the nested list.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively check sublists
        else:
            max_value = max(max_value, item)

    return max_value


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)

print("Maximum element:", result)

Maximum element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A list that may contain elements or other nested lists.
    elem (any): The element whose occurrences need to be counted.

    Returns:
    int: Total number of times elem appears in the nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        else:
            if item == elem:
                count += 1

    return count


# Example usage
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)

print("Number of occurrences:", result)

Number of occurrences: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
    lst (list): A list that may contain elements or other nested lists.

    Returns:
    list: A flattened list containing all elements in a single dimension.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            result.append(item)

    return result


# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(nested_list)

print("Flattened list:", output)

Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculate the average of all numbers in a nested list.

    Parameters:
    lst (list): A list that may contain numbers or other nested lists.

    Returns:
    float: The average of all numbers in the nested list.
    """
    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total, count


# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]

total, count = average_nested(nested_list)
average = total / count

print("Average:", average)

Average: 3.5


10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. Ones array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type filled with a value
full_array = np.full((3, 3), 7)
print("\n3. Array filled with value 7:")
print(full_array)

# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(full_array)
print("\n4. Zeros array with same shape as full_array:")
print(zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(full_array)
print("\n5. Ones array with same shape as full_array:")
print(ones_like_array)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. List converted to NumPy array:")
print(numpy_array)

1. Empty array (2x2):
[[6.75088581e-316 0.00000000e+000]
 [6.94743175e-316 7.90505033e-323]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as full_array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones array with same shape as full_array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List converted to NumPy array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:")
print(arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(arr3)

# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
print("\n4. Random array of size 30:")
print(arr4)
print("Mean:", arr4.mean())

# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
print("\n5. 10x10 random array:")
print(arr5)
print("Minimum value:", arr5.min())
print("Maximum value:", arr5.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element replaced by 1:")
print(arr6)

# 7. Reverse an array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:")
print(arr8)

# 9. Create an 8x8 checkerboard pattern
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:")
print(arr9)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.19207132 0.7270452  0.82969436 0.36795176 0.28212187 0.51585551
 0.96485743 0.474557   0.17992765 0.98046775 0.18116766 0.5037667
 0.46600071 0.79640177 0.19779861 0.31046264 0.43602627 0.0248289
 0.18080886 0.54259439 0.87418355 0.49791858 0.67214225 0.35387597
 0.68787808 0.17602022 0.26376586 0.84439999 0.0071062  0.38363274]
Mean: 0.46384432640459167

5. 10x10 random array:
[[0.2916349  0.52611835 0.84511834 0.52349805 0.30273648 0.01744431
  0.22401314 0.14750957 0.71037395 0.85618365]
 [0.74475871 0.43714748 0.10005616 0.8183078  0.68891885 0.66658618
  0.658585   0.61157962 0.09719685 0.34071771]
 [0.0637009  0.24572075 0.03952312 0.33361295 0.01406627 0.44460658
  0.66479484 0.96617077 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [1]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
print("1. Addition of x and y:")
print(x + y)

# 2. Subtract the two arrays
print("\n2. Subtraction of x and y:")
print(x - y)

# 3. Multiply the array with an integer
print("\n3. Multiply x with 2:")
print(x * 2)

# 4. Square of each element
print("\n4. Square of elements in x:")
print(x ** 2)

# 5. Dot products
print("\n5. Dot product v and w:")
print(np.dot(v, w))

print("\nDot product x and v:")
print(np.dot(x, v))

print("\nDot product x and y:")
print(np.dot(x, y))

# 6. Concatenate arrays
print("\n6. Concatenate x and y along rows:")
print(np.concatenate((x, y), axis=0))

print("\nConcatenate v and w along column:")
print(np.vstack((v, w)))

# 7. Concatenate x and v
    print(np.concatenate((x, v)))

IndentationError: unexpected indent (1773627161.py, line 44)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A^-1:")
print(identity)
print("Check if identity (approx.):", np.allclose(identity, np.eye(2)))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:")
print(AB)
print("BA:")
print(BA)
print("Check AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = (AB).T
B_TA_T = np.dot(B.T, A.T)
print("\n3. (AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(B_TA_T)
print("Check equality:", np.array_equal(AB_T, B_TA_T))

# -----------------------------
# Solve system of linear equations
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent in matrix form: AX = B
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
B_vec = np.array([-1, -3, 9])

# Solve using np.linalg.inv
X = np.dot(np.linalg.inv(coeff_matrix), B_vec)
print("\nSolution using inverse method:")
print("x, y, z =", X)

1. A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Check if identity (approx.): True

2. AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Check AB == BA: False

3. (AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Check equality: True

Solution using inverse method:
x, y, z = [ 2.  1. -2.]
